### PR TITLE
Several improvements to codebase

### PR DESCRIPTION
**Pull request by Qix-**
Had some downtime and saw this in my activity feed, figured I'd lend a hand for some low-hanging C/Make stuff.

- Added proper platform detection in `config.mk` -- `/usr/local/include` is generally implicitly added as a system include directory, as is `/usr/local/lib` as a library directory. I assumed MinGW on windows needed special treatment so I left those settings intact on such platforms (the `ifeq ($(OS)...` check might need testing)
- Added a `.gitignore` as your object files/binaries shouldn't be included in git repositories - also removed such files from the repository
- Added MacOS build instructions
- Added `-f` on `rm`, since without `-f` `rm` will fail and not do much of anything if one or more of the paths don't exist (which, when cleaning, you don't care about). `-f` means "try and quietly fail if one or all of the paths don't exist".
- Make the `libxml2` path a system path so it's treated as such. Why it doesn't get installed properly is beyond me - seems like an error on the package maintainer's end.

Hope this helps :)

### CODE REVIEW

**Comment by mupfdev** [comment]
Hey Qix, I didn't saw your pull request for some reason but I will review your recommendations as soon I can find the some some peace and quite. And apparently I also created some conflicts with my last pull requests. Anyway: thank you, I really appreciate it!

**Review by mupfdev — APPROVED** [review]

**Review by mupfdev — APPROVED** [review]

**Review by mupfdev — APPROVED** [review]

**Review by mupfdev — CHANGES_REQUESTED** [review]
The GCC option `-licuuc` can safely be removed. Therefore: the game might not even depend on icu4c. Can you confirm this on MacOS?

I'm also not certain about the OS detection. And because I do not use Mingw-w64 on Windows, I can not even give it a try. I compile my Windows binaries using an Arch Linux virtual machine.

**Review by mupfdev — APPROVED** [review]
I didn't knew about that option. Thanks.

**Comment by Qix-** [comment]
`-licu4c` is required on MacOS - I tried building on mac and it didn't work without it :)

**Review by mupfdev — APPROVED** [review]

**Comment by mupfdev** [comment]
Merged.
Thanks again for your time and interest. :+1:

**Pull request merged**
